version: "3"
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    container_name: ipfs
    environment:
      - IPFS_PROFILE=${IPFS_PROFILE:-server}
      - LIBP2P_FORCE_PNET=1
    volumes:
      - ./staging:/export
      - ./data:/data/ipfs
    ports:
      - 4001:4001
      - 4001:4001/udp
      - 127.0.0.1:8080:8080
      - 127.0.0.1:5001:5001
