version: "3.7"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    hostname: zoo1
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    env_file:
      - kafka/kafka-variables.env
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "8082:8082"
      - "8083:8083"

  mongodb:
    image: mongo:4.0
    ports:
      - "27017:27017"

  consumer-mongodb:
    build:
      context: consumer-mongodb
    environment:
      mongoURL: mongodb://mongo-db:27017
      dbName: example_db
      collectionName: example_coll
      kafkaURL: kafka:9092
      topic: topic1
      GroupID: mongo-group
    depends_on:
      - kafka
      - mongo-db

  consumer-logger:
    build:
      context: consumer-logger
    environment:
      kafkaURL: kafka:9092
      topic: topic1
      GroupID: logger-group
    depends_on:
      - kafka

  producer-random:
    build:
      context: producer-random
    environment:
      kafkaURL: kafka:9092
      topic: topic1
    depends_on:
      - kafka

  producer-api:
    build:
      context: producer-api
    environment:
      kafkaURL: kafka:9092
      topic: topic1
    ports:
      - "8080:8080"
    depends_on:
      - kafka
