// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Order struct {
	OrderId              string             `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Status               string             `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	CreatedOn            int64              `protobuf:"varint,3,opt,name=created_on,json=createdOn,proto3" json:"created_on,omitempty"`
	OrderItems           []*Order_OrderItem `protobuf:"bytes,4,rep,name=order_items,json=orderItems,proto3" json:"order_items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetCreatedOn() int64 {
	if m != nil {
		return m.CreatedOn
	}
	return 0
}

func (m *Order) GetOrderItems() []*Order_OrderItem {
	if m != nil {
		return m.OrderItems
	}
	return nil
}

type Order_OrderItem struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	UnitPrice            float32  `protobuf:"fixed32,3,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Quantity             uint32   `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order_OrderItem) Reset()         { *m = Order_OrderItem{} }
func (m *Order_OrderItem) String() string { return proto.CompactTextString(m) }
func (*Order_OrderItem) ProtoMessage()    {}
func (*Order_OrderItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0, 0}
}

func (m *Order_OrderItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order_OrderItem.Unmarshal(m, b)
}
func (m *Order_OrderItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order_OrderItem.Marshal(b, m, deterministic)
}
func (m *Order_OrderItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order_OrderItem.Merge(m, src)
}
func (m *Order_OrderItem) XXX_Size() int {
	return xxx_messageInfo_Order_OrderItem.Size(m)
}
func (m *Order_OrderItem) XXX_DiscardUnknown() {
	xxx_messageInfo_Order_OrderItem.DiscardUnknown(m)
}

var xxx_messageInfo_Order_OrderItem proto.InternalMessageInfo

func (m *Order_OrderItem) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Order_OrderItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Order_OrderItem) GetUnitPrice() float32 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

func (m *Order_OrderItem) GetQuantity() uint32 {
	if m != nil {
		return m.Quantity
	}
	return 0
}

type OrderResponse struct {
	IsSuccess            bool     `protobuf:"varint,1,opt,name=is_success,json=isSuccess,proto3" json:"is_success,omitempty"`
	Error                string   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func (m *OrderResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type OrderFilter struct {
	SearchText           string   `protobuf:"bytes,1,opt,name=search_text,json=searchText,proto3" json:"search_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderFilter) Reset()         { *m = OrderFilter{} }
func (m *OrderFilter) String() string { return proto.CompactTextString(m) }
func (*OrderFilter) ProtoMessage()    {}
func (*OrderFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{2}
}

func (m *OrderFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderFilter.Unmarshal(m, b)
}
func (m *OrderFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderFilter.Marshal(b, m, deterministic)
}
func (m *OrderFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderFilter.Merge(m, src)
}
func (m *OrderFilter) XXX_Size() int {
	return xxx_messageInfo_OrderFilter.Size(m)
}
func (m *OrderFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderFilter.DiscardUnknown(m)
}

var xxx_messageInfo_OrderFilter proto.InternalMessageInfo

func (m *OrderFilter) GetSearchText() string {
	if m != nil {
		return m.SearchText
	}
	return ""
}

type ServiceDiscovery struct {
	OrderServiceUri      string   `protobuf:"bytes,1,opt,name=order_service_uri,json=orderServiceUri,proto3" json:"order_service_uri,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceDiscovery) Reset()         { *m = ServiceDiscovery{} }
func (m *ServiceDiscovery) String() string { return proto.CompactTextString(m) }
func (*ServiceDiscovery) ProtoMessage()    {}
func (*ServiceDiscovery) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{3}
}

func (m *ServiceDiscovery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceDiscovery.Unmarshal(m, b)
}
func (m *ServiceDiscovery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceDiscovery.Marshal(b, m, deterministic)
}
func (m *ServiceDiscovery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceDiscovery.Merge(m, src)
}
func (m *ServiceDiscovery) XXX_Size() int {
	return xxx_messageInfo_ServiceDiscovery.Size(m)
}
func (m *ServiceDiscovery) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceDiscovery.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceDiscovery proto.InternalMessageInfo

func (m *ServiceDiscovery) GetOrderServiceUri() string {
	if m != nil {
		return m.OrderServiceUri
	}
	return ""
}

type EventStore struct {
	AggregateId          string   `protobuf:"bytes,1,opt,name=aggregate_id,json=aggregateId,proto3" json:"aggregate_id,omitempty"`
	AggregateType        string   `protobuf:"bytes,2,opt,name=aggregate_type,json=aggregateType,proto3" json:"aggregate_type,omitempty"`
	EventId              string   `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	EventType            string   `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventData            string   `protobuf:"bytes,5,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventStore) Reset()         { *m = EventStore{} }
func (m *EventStore) String() string { return proto.CompactTextString(m) }
func (*EventStore) ProtoMessage()    {}
func (*EventStore) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{4}
}

func (m *EventStore) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventStore.Unmarshal(m, b)
}
func (m *EventStore) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventStore.Marshal(b, m, deterministic)
}
func (m *EventStore) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventStore.Merge(m, src)
}
func (m *EventStore) XXX_Size() int {
	return xxx_messageInfo_EventStore.Size(m)
}
func (m *EventStore) XXX_DiscardUnknown() {
	xxx_messageInfo_EventStore.DiscardUnknown(m)
}

var xxx_messageInfo_EventStore proto.InternalMessageInfo

func (m *EventStore) GetAggregateId() string {
	if m != nil {
		return m.AggregateId
	}
	return ""
}

func (m *EventStore) GetAggregateType() string {
	if m != nil {
		return m.AggregateType
	}
	return ""
}

func (m *EventStore) GetEventId() string {
	if m != nil {
		return m.EventId
	}
	return ""
}

func (m *EventStore) GetEventType() string {
	if m != nil {
		return m.EventType
	}
	return ""
}

func (m *EventStore) GetEventData() string {
	if m != nil {
		return m.EventData
	}
	return ""
}

func init() {
	proto.RegisterType((*Order)(nil), "pb.Order")
	proto.RegisterType((*Order_OrderItem)(nil), "pb.Order.OrderItem")
	proto.RegisterType((*OrderResponse)(nil), "pb.OrderResponse")
	proto.RegisterType((*OrderFilter)(nil), "pb.OrderFilter")
	proto.RegisterType((*ServiceDiscovery)(nil), "pb.ServiceDiscovery")
	proto.RegisterType((*EventStore)(nil), "pb.EventStore")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 442 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x86, 0x37, 0xfd, 0x58, 0x9a, 0xc9, 0x96, 0x65, 0x0d, 0x42, 0xa1, 0x12, 0xa2, 0x44, 0x42,
	0xaa, 0x40, 0x54, 0x68, 0xe1, 0xcc, 0x85, 0x02, 0xea, 0xa9, 0x28, 0x5d, 0xce, 0x91, 0x9b, 0x8c,
	0x8a, 0x11, 0x8d, 0x83, 0x3d, 0xa9, 0xb6, 0xbf, 0x8a, 0x9f, 0xc8, 0xca, 0x63, 0x37, 0xed, 0xa5,
	0x9a, 0x79, 0xde, 0xce, 0x47, 0xc6, 0x2f, 0x24, 0xda, 0x54, 0x68, 0xe6, 0x8d, 0xd1, 0xa4, 0x45,
	0xaf, 0xd9, 0x64, 0xff, 0x23, 0x18, 0xae, 0x1c, 0x13, 0x2f, 0x60, 0xc4, 0x62, 0xa1, 0xaa, 0x34,
	0x9a, 0x46, 0xb3, 0x38, 0x7f, 0xc4, 0xf9, 0xb2, 0x12, 0xcf, 0xe1, 0xd2, 0x92, 0xa4, 0xd6, 0xa6,
	0x3d, 0x16, 0x42, 0x26, 0x5e, 0x02, 0x94, 0x06, 0x25, 0x61, 0x55, 0xe8, 0x3a, 0xed, 0x4f, 0xa3,
	0x59, 0x3f, 0x8f, 0x03, 0x59, 0xd5, 0xe2, 0x53, 0x18, 0x57, 0x28, 0xc2, 0x9d, 0x4d, 0x07, 0xd3,
	0xfe, 0x2c, 0xb9, 0x7d, 0x3a, 0x6f, 0x36, 0x73, 0x9e, 0xe8, 0x7f, 0x97, 0x84, 0xbb, 0x1c, 0xf4,
	0x31, 0xb4, 0x93, 0x1a, 0xe2, 0x4e, 0x10, 0x02, 0x06, 0xa5, 0xae, 0x30, 0x2c, 0xc4, 0xb1, 0x63,
	0xb5, 0xdc, 0x61, 0xd8, 0x85, 0x63, 0xb7, 0x49, 0x5b, 0x2b, 0x2a, 0x1a, 0xa3, 0x4a, 0xe4, 0x4d,
	0x7a, 0x79, 0xec, 0xc8, 0x0f, 0x07, 0xc4, 0x04, 0x46, 0x7f, 0x5b, 0x59, 0x93, 0xa2, 0x43, 0x3a,
	0x98, 0x46, 0xb3, 0x71, 0xde, 0xe5, 0xd9, 0x02, 0xc6, 0x3c, 0x2f, 0x47, 0xdb, 0xe8, 0xda, 0x72,
	0x2f, 0x65, 0x0b, 0xdb, 0x96, 0x25, 0x5a, 0xcb, 0x93, 0x47, 0x79, 0xac, 0xec, 0xda, 0x03, 0xf1,
	0x0c, 0x86, 0x68, 0x8c, 0x36, 0x61, 0xbe, 0x4f, 0xb2, 0x39, 0x24, 0xdc, 0xe5, 0x9b, 0xfa, 0x43,
	0x68, 0xc4, 0x2b, 0x48, 0x2c, 0x4a, 0x53, 0xfe, 0x2a, 0x08, 0xef, 0x29, 0xac, 0x0f, 0x1e, 0xdd,
	0xe1, 0x3d, 0x65, 0x9f, 0xe1, 0xc9, 0x1a, 0xcd, 0x5e, 0x95, 0xb8, 0x50, 0xb6, 0xd4, 0x7b, 0x34,
	0x07, 0xf1, 0x16, 0x6e, 0xfc, 0xbd, 0xac, 0x57, 0x8a, 0xd6, 0xa8, 0x50, 0x7a, 0xcd, 0x42, 0xa8,
	0xf8, 0x69, 0x54, 0xf6, 0x2f, 0x02, 0xf8, 0xba, 0xc7, 0x9a, 0xd6, 0xa4, 0x0d, 0x8a, 0xd7, 0x70,
	0x25, 0xb7, 0x5b, 0x83, 0x5b, 0x49, 0x78, 0x7a, 0xc0, 0xa4, 0x63, 0xcb, 0x4a, 0xbc, 0x81, 0xc7,
	0xa7, 0xbf, 0xd0, 0xa1, 0x39, 0x1e, 0x70, 0xdc, 0xd1, 0xbb, 0x43, 0x83, 0xce, 0x06, 0xe8, 0xfa,
	0xba, 0x2e, 0x7d, 0x6f, 0x03, 0xce, 0x97, 0x95, 0x3b, 0x8c, 0x97, 0xb8, 0x7a, 0xc0, 0x62, 0xcc,
	0x84, 0x2b, 0x3b, 0xb9, 0x92, 0x24, 0xd3, 0xe1, 0x99, 0xbc, 0x90, 0x24, 0x6f, 0x7f, 0xc3, 0xd5,
	0xea, 0xec, 0x23, 0xc4, 0x3b, 0x88, 0xbf, 0x23, 0x31, 0xb2, 0xe2, 0xba, 0x73, 0x85, 0x3f, 0xe0,
	0x24, 0xee, 0x40, 0x76, 0xf1, 0x21, 0x12, 0xef, 0x21, 0xf9, 0xc2, 0xbe, 0xf2, 0x5e, 0x3d, 0xa9,
	0x93, 0x9b, 0x2e, 0x3c, 0x3e, 0x60, 0x76, 0xb1, 0xb9, 0x64, 0x83, 0x7f, 0x7c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x23, 0xac, 0x67, 0x24, 0xef, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	GetOrders(ctx context.Context, in *OrderFilter, opts ...grpc.CallOption) (OrderService_GetOrdersClient, error)
	CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) GetOrders(ctx context.Context, in *OrderFilter, opts ...grpc.CallOption) (OrderService_GetOrdersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_OrderService_serviceDesc.Streams[0], "/pb.OrderService/GetOrders", opts...)
	if err != nil {
		return nil, err
	}
	x := &orderServiceGetOrdersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderService_GetOrdersClient interface {
	Recv() (*Order, error)
	grpc.ClientStream
}

type orderServiceGetOrdersClient struct {
	grpc.ClientStream
}

func (x *orderServiceGetOrdersClient) Recv() (*Order, error) {
	m := new(Order)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OrderResponse, error) {
	out := new(OrderResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	GetOrders(*OrderFilter, OrderService_GetOrdersServer) error
	CreateOrder(context.Context, *Order) (*OrderResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) GetOrders(req *OrderFilter, srv OrderService_GetOrdersServer) error {
	return status.Errorf(codes.Unimplemented, "method GetOrders not implemented")
}
func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *Order) (*OrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_GetOrders_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderFilter)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderServiceServer).GetOrders(m, &orderServiceGetOrdersServer{stream})
}

type OrderService_GetOrdersServer interface {
	Send(*Order) error
	grpc.ServerStream
}

type orderServiceGetOrdersServer struct {
	grpc.ServerStream
}

func (x *orderServiceGetOrdersServer) Send(m *Order) error {
	return x.ServerStream.SendMsg(m)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetOrders",
			Handler:       _OrderService_GetOrders_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "order.proto",
}
